### ISSUE TITLE
Initial debug logs not being output

### ISSUE THREAD

**Issue by bmulvihill** [crystal-lang-tools/scry#121]
Currently we log the messages coming from the LSP client for debugging purposes here:

https://github.com/crystal-lang-tools/scry/blob/26a1e431c3f3b1dac87adac11af6ddf5ee6ee42c/src/scry/request.cr#L43-L47

The problem is we receive some messages (i.e. initialization and user configs) prior to the log level being set by the User settings (which is how we currently change the log level).  The default log level is `INFO` so these messages will never get logged.

**Comment by faustinoaq** [comment]
Also diagnostic responses are not logged, may be related, WDYT?
