### ISSUE TITLE
https://github.com/crystal-lang/crystal/issues/7151

### ISSUE THREAD

**Issue by patleb** [crystal-lang-tools/scry#148]
Just redirecting the [issue](https://github.com/crystal-lang/crystal/issues/7151) here. It seems that the last part of the identifier is duplicated infinitely which causes the error.

Until this issue is taking care of, just setting the logger level to 'fatal' keeps VSCode happy:

```json
"crystal-lang.logLevel": "fatal",
```

**Comment by bmulvihill** [comment]
@patleb What version of scry are you using?

**Comment by patleb** [comment]
This commit 404dcc0d9d92802828c05e7815951e51a3ffd2f8 on master

**Comment by matthewmcgarvey** [comment]
I'm unable to reproduce.  Is this issue continuing if you turned the logLevel back up?  What if you moved your code to a different location not nested in the `.crystal` folder?

**Comment by patleb** [comment]
Yes, still there, at the most recent commit. It's not nested in the `.crystal` folder. Sorry, I should have given some details.

It happens when I use Amber, it wasn't happening with Kemal. It looks like it has something to do with macros.

**Comment by patleb** [comment]
And it's through VSCode

**Comment by patleb** [comment]
I think it's crystal that generate the `.crystal` code when expanding macros (and probably for other stuff too, like `require`), not totally sure, but it looks like it. Is that directory should be ignored by `scry`?
