### ISSUE TITLE
This library should have a set of benchmarks

### ISSUE THREAD

**Issue by matthewmcgarvey** [crystal-lang-tools/scry#153]
Is it just me or is scry slow?  I find that it almost never is helpful for completions and building the project on the command line can sometimes be quicker feedback for compile errors.  I'd like to work on this but I have no idea which piece to attack first.  If we could come up with a way of doing benchmarks for this library I'd be happy to start writing them.

**Comment by bew** [comment]
I also agree, it's slow... It's unusable for me in vim (error reporting is almost always outdated, and completion isn't complete...

#163 should help i think, but didn't start it yet
