### ISSUE TITLE
Prelude Error Message

### ISSUE THREAD

**Issue by iambudi** [crystal-lang-tools/scry#173]
After upgrading crystal to 0.35.0, scry gives the following errors for any `.cr` files open in vscode:

```bash
can't find file 'prelude'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?Scry
```

Any way to exclude the error?

**Comment by Reikion** [comment]
https://crystal-lang.org/2020/06/09/crystal-0.35.0-released.html#compiler
> Another breaking-change use for some shell integrations is that crystal env will now quote the values.
```
diff --git a/src/scry/environment_config.cr b/src/scry/environment_config.cr
index 34e3fb0..f5787d4 100644
--- a/src/scry/environment_config.cr
+++ b/src/scry/environment_config.cr
@@ -10,7 +11,6 @@ module Scry
       crystal_env
         .lines
         .map(&.split('='))
-        .map { |(k, v)| {k, v.chomp[1..-2]} }
         .to_h
     end
```
I'll make proper pull request later

**Comment by iambudi** [comment]
Hi @Reikion,

Thanks a lot. Removing `.map { |(k, v)| {k, v.chomp[1..-2]} }` as you did and recompile, scry does not throw prelude error any longer.

A pull request should be made since this prelude error is quite annoying.
