### ISSUE TITLE
Use static linked binaries

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/scry#22]
Many people have problems to compile Scry even to execute the releases binaries.

Maybe we can link it statically using docker image.

I was able to compile Scry staticaly using official Crystal docker image and the binary runs without dependencies in almost every distro: ArchLnux, Ubuntu, Centos. (not Alpine)

To compile statically we can use `crystal build src/scry.cr --link-flags="-static"` on Linux.

What do you think guys?

**Comment by kofno** [comment]
Won't static linking increase the size of the binary? I'm not against it, necessarily, but that is a possible drawback.

**Comment by faustinoaq** [comment]
Well, you are right, the Scry size of static linked binary is almost five
times bigger on Linux.

>>> crystal build -p -s src/scry.cr --link-flags="-static"
>>> ls -lh scry
-rwxr-xr-x 1 root root 54M Aug 21 13:55 scry

But runs almost anywhere :-)

**Comment by faustinoaq** [comment]
I tried some options like `release` and `no-debug` and I got:

```
$ crystal build -p -s src/scry.cr --link-flags="-static"
$ ls -hl scry*
-rwxr-xr-x 1 root root 54M Aug 23 01:01 scry
$ crystal build src/scry.cr -s -p --release --no-debug --link-flags="-static"
$ ls -hl scry*
-rwxr-xr-x 1 root root 45M Aug 23 01:34 scry
$ strip -s scry
-rwxr-xr-x 1 root root 40M Aug 23 01:35 scry
```

So, even with striped symbols Scry size is 4x when compiled statically.

Currently, I'm able to run release binary for Linux in Ubuntu and similar distros.

I think in other distros like ArchLinux, users should compile Scry using `crystal build src/scry.cr` instead.
