### ISSUE TITLE
Support mainFile setting

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/scry#29]
Some projects could have a main file, avoiding `require`'s in every file. So instead of analyzing each file, with `mainFile` option we can analyze just one. [0] By example, on amber projects [1]

[0] - https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings#mainfile
[1] - https://github.com/amberframework/amberframework.org/blob/master/src/amberframework.cr#L5

**Comment by faustinoaq** [comment]
> Support `main_file = "src/*.cr"` as mainFile requiring all in a temp file `crystal tool implementations -C src/foo/bar.cr:line:col /path/for/tmp.cr`

A good recommendation by @Papierkorb

**Comment by bew** [comment]
Where would be stored this configuration variable?

**Comment by faustinoaq** [comment]
> Where would be stored this configuration variable?

@bew This was the first idea about allowing implicit requires, Currently to get scry diagnostics properly you must require all needed files, because scry doesn't analyze per project but per file.

I think should be some other way to allow implicit requires
