### ISSUE TITLE
Missing `id` in ResponseError

### ISSUE THREAD

**Issue by bew** [crystal-lang-tools/scry#52]
When an error happens during a RPC call, a `ResponseMessage` is returned, without the message id it's currently in processing.
https://github.com/crystal-lang-tools/scry/blob/a2ac15c6d810c319c59aebc3c92d1a7bec866613/src/scry/protocol/response_error.cr#L20-L30
This makes the Language Client for Neovim crash for the request.

I looked at the code, the important bit is https://github.com/crystal-lang-tools/scry/blob/a2ac15c6d810c319c59aebc3c92d1a7bec866613/src/scry.cr#L20-L29
At line 25, the `ResponseMessage` object will create a `ReponseError` with the given exception.
But the current request's ID we are processing is lost.

**Comment by faustinoaq** [comment]
@bew Thank you for reporting this issue!

Maybe we can try to return/asign the request id as well:

```crystal
{request, id} = Message.new(content).parse 
# and
results = [ResponseMessage.new(ex, id)] 
```

**Comment by bew** [comment]
Yes something like this, and/or move the request parsing out of the `begin ... rescue` ? I think that if the request is malformed by the client, it should just crash. This way you can access `request.id` (or something like that) safely inside the rescue.

What do you think?

**Comment by bew** [comment]
I'm not sure what you mean by `malformed url`, I was talking about malformed json rpc request, for example a bad json that cannot parse, or which does not have an `id` for the request.
If there is at least an `id` in the request, we should be able to reply with the correct id.

**Comment by faustinoaq** [comment]
Oh, I was a bit confused, sorry for my confused comment :sweat_smile: 

I tried to make a reference to [Error responses](https://github.com/crystal-lang-tools/scry/blob/1bff42ea0624eb991f11a7a90307a49fe4dce6cf/src/scry/protocol/response_error.cr#L20) 

> If there is at least an id in the request, we should be able to reply with the correct id.

I agree, in fact I tried to return the id in some PRs some time ago, but scry didn't compile, so I removed it :sweat_smile:
