### ISSUE TITLE
Add ameba to ci

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/scry#58]
> Ameba is a static code analysis tool for the Crystal language. It enforces a consistent Crystal code style, also catches code smells and wrong code constructions

https://github.com/veelenga/ameba

[![ameba](https://gitcdn.link/repo/veelenga/bin/master/ameba/logo.png)](https://github.com/veelenga/ameba "Ameba tool for Crystal")

See #57

**Comment by veelenga** [comment]
Is this ticket about using Ameba to lint the scry code or support it via LSP? Some discussion started here:

https://github.com/veelenga/ameba/issues/37

**Comment by faustinoaq** [comment]
> Is this ticket about using Ameba to lint the scry code or support it via LSP?

@veelenga Currently the idea is using ameba on Travis like amber is doing

**Comment by faustinoaq** [comment]
> support it via LSP?

Seems an interesting idea, Thank for sharing! :+1:
