### ISSUE TITLE
Completion: Dependancy graph and method db should be updated when there import changes

### ISSUE THREAD

**Issue by laginha87** [crystal-lang-tools/scry#61]
if you have this scenario.
```crystal
# File b.cr
class A
   def self.a
   end
end
```

```crystal
# File a.cr
```

and then change file a.cr to:

```crystal
# File a.cr
require "./b"
A.
```

Completion on A. doesn't work. 
This is because the dependancy to b.cr wasn't added to the file.
We can either change this on save or on update. But I think on update might be really slow.

**Comment by faustinoaq** [comment]
@laginha87 Is this fixed? :sweat_smile:

**Comment by faustinoaq** [comment]
I think we can execute something similar to `@workspace.open_workspace` here: https://github.com/crystal-lang-tools/scry/blob/master/src/scry/context.cr#L165

Perhaps  just ignoring existent files and adding new ones, WDYT?
