### ISSUE TITLE
Crystal URL Scheme

### ISSUE THREAD

**Issue by Proximyst** [crystal-lang-tools/scry#68]
It's not like it's a big issue or anything, but it kind of bugs me. The Crystal URL in the "topic"/"description" of the repository uses HTTP, while the site uses HTTPS. Granted it redirects, it looks kind of bad to me and anyone alike me.

**Comment by faustinoaq** [comment]
![screenshot_20180327_184231](https://user-images.githubusercontent.com/3067335/38000732-9c52a3fe-31ee-11e8-9bf6-3357efaa7deb.png)

Fixed :+1:
