### ISSUE TITLE
Add test for the compiled binary itself

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/scry#73]
After working on #48 I realize our specs don't test the working binary, just the isolated code of scry modules and features.

My proposal is to create a spec for testing the compiled binary, simulating a client to writing the input, checking output and to get the right response.

**Comment by bew** [comment]
Another way would be to isolate scry behind a class with input io, output io (and error io and/or logger?), so that you can unit test it using some `IO::Memory`.
Also this would make scry config easier I think (e.g: all in a cli.cr file, that would configure the Scry instance).
